# Generated by Django 6.0.3 on 2026-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
