# Generated by Django 6.0.3 on 2026-04-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_stripe_price_id_monthly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_monthly',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_yearly',
        ),
        migrations.RemoveField(
            model_name='workspacesubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='workspacesubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_plan_id_monthly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_plan_id_yearly',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
