# Generated by Django 6.0.3 on 2026-04-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_plan_workspacesubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacesubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='workspacesubscription',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='WorkspaceSubscription',
        ),
    ]
