# Generated by Django 6.0.3 on 2026-05-05 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_workspacesubscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 5, 14, 47, 29, 27524, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
